name: reworkutils
description: 
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path_provider: ^2.0.1
  device_info_plus: ^4.1.2
  flutter_image_compress: ^1.1.3
  image_pickers: ^2.0.0+2
  image_picker: ^0.8.5+3
  package_info_plus: ^1.4.3+1
  http: ^0.13.5
  shared_preferences:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

